// flow-typed signature: 2a65bf94e99ad098da4d6a448082ae2c
// flow-typed version: <<STUB>>/fbgraph_v^1.4.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fbgraph'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fbgraph' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fbgraph/lib/graph' {
  declare module.exports: any;
}

declare module 'fbgraph/tests/config' {
  declare module.exports: any;
}

declare module 'fbgraph/tests/graph.test' {
  declare module.exports: any;
}

declare module 'fbgraph/tests/testUsers.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fbgraph/index' {
  declare module.exports: $Exports<'fbgraph'>;
}
declare module 'fbgraph/index.js' {
  declare module.exports: $Exports<'fbgraph'>;
}
declare module 'fbgraph/lib/graph.js' {
  declare module.exports: $Exports<'fbgraph/lib/graph'>;
}
declare module 'fbgraph/tests/config.js' {
  declare module.exports: $Exports<'fbgraph/tests/config'>;
}
declare module 'fbgraph/tests/graph.test.js' {
  declare module.exports: $Exports<'fbgraph/tests/graph.test'>;
}
declare module 'fbgraph/tests/testUsers.test.js' {
  declare module.exports: $Exports<'fbgraph/tests/testUsers.test'>;
}
